import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ArrowLeft, CheckCircle, XCircle, Play, Trophy,
  Factory, Package, Hash, Calendar, ClipboardList, Info,
} from 'lucide-react';
import { PageWrapper, formatDate, formatDateTime } from '../../components/UI';
import StatusBadge from '../../components/StatusBadge';
import { manufacturingApi } from '../../utils/api';
import { useAuth } from '../../context/AuthContext';
import { useToast } from '../../context/ToastContext';

function labelStatus(s) {
  const M = { 
    DRAFT:'Draft', 
    WAITING_FOR_MATERIALS: 'Waiting Materials', 
    READY_FOR_PRODUCTION: 'Ready', 
    IN_PRODUCTION:'In Production', 
    COMPLETED:'Completed', 
    CANCELLED:'Cancelled' 
  };
  return M[s] ?? s;
}

const STATUS_STEPS = ['Draft', 'Waiting Materials', 'Ready', 'In Production', 'Completed'];

export default function ManufacturingDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const toast = useToast();

  const [order, setOrder] = useState(null);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState(false);
  const [modal, setModal] = useState(null); // 'confirm' | 'start' | 'complete'

  const fetchOrder = useCallback(async () => {
    setLoading(true);
    try {
      const res = await manufacturingApi.getById(id);
      setOrder(res?.data ?? res);
    } catch { toast('Order not found', 'error'); navigate('/manufacturing'); }
    finally { setLoading(false); }
  }, [id, navigate, toast]);

  useEffect(() => { fetchOrder(); }, [fetchOrder]);

  const doAction = async (actionFn, successMsg, modalName) => {
    setActionLoading(true);
    try {
      await actionFn();
      toast(successMsg, 'success');
      setModal(null);
      fetchOrder();
    } catch (err) {
      toast(err.message || 'Action failed', 'error');
    } finally {
      setActionLoading(false);
    }
  };

  if (loading) return (
    <PageWrapper><div className="flex items-center justify-center py-20">
      <span className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin" />
    </div></PageWrapper>
  );
  if (!order) return null;

  const status = order.status;
  const components = order.components ?? order.bom?.components ?? [];
  const workOrders = order.workOrders ?? [];

  const currentStep = { DRAFT: 0, WAITING_FOR_MATERIALS: 1, READY_FOR_PRODUCTION: 2, IN_PRODUCTION: 3, COMPLETED: 4, CANCELLED: -1 }[status] ?? 0;

  return (
    <PageWrapper>
      <div className="page-header">
        <div className="flex items-center gap-3">
          <button onClick={() => navigate('/manufacturing')} className="btn-ghost btn-icon">
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div>
            <div className="flex items-center gap-3">
              <h1 className="page-title font-mono">{order.orderNumber ?? order.id}</h1>
              <StatusBadge status={labelStatus(status)} />
              {order.autoGenerated && (
                <span className="text-xs px-2 py-0.5 rounded-full bg-warning/10 text-warning border border-warning/30 font-medium">Auto-Generated</span>
              )}
            </div>
            <p className="page-subtitle">{order.product?.name ?? '—'} · Qty: {order.quantity}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {(status === 'DRAFT' || status === 'WAITING_FOR_MATERIALS') && (
            <button onClick={() => setModal('check')} className="btn-primary">
              <Package className="w-4 h-4" />Check Availability
            </button>
          )}
          {status === 'READY_FOR_PRODUCTION' && (
            <button onClick={() => setModal('start')} className="btn-warning">
              <Play className="w-4 h-4" />Start Production
            </button>
          )}
          {status === 'IN_PRODUCTION' && (
            <button onClick={() => setModal('complete')} className="btn-success">
              <Trophy className="w-4 h-4" />Complete
            </button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          {/* Order Info */}
          <motion.div className="card" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
            <h2 className="text-sm font-semibold text-text-primary mb-4 flex items-center gap-2">
              <ClipboardList className="w-4 h-4 text-primary" />Order Information
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
              {[
                { icon: Hash,    label: 'MO Number', value: order.orderNumber ?? order.id, mono: true },
                { icon: Factory, label: 'Product',   value: order.product?.name ?? '—' },
                { icon: Package, label: 'Quantity',  value: order.quantity },
                { icon: Calendar,label: 'Created',   value: formatDate(order.createdAt) },
                { icon: Info,    label: 'Status',    value: <StatusBadge status={labelStatus(status)} /> },
                { icon: Factory, label: 'BoM',       value: order.bom?.name ?? '—' },
              ].map(item => (
                <div key={item.label} className="flex flex-col gap-1">
                  <div className="flex items-center gap-1.5 text-xs text-text-muted">
                    <item.icon className="w-3.5 h-3.5" />{item.label}
                  </div>
                  <div className={`text-sm ${item.mono ? 'font-mono text-primary font-semibold' : 'text-text-primary'}`}>
                    {item.value}
                  </div>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Missing Materials Alert */}
          {status === 'WAITING_FOR_MATERIALS' && order.linkedPurchaseOrders?.length > 0 && (
            <motion.div className="p-4 rounded-xl bg-orange-50 border border-orange-200" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
              <div className="flex items-center gap-2 mb-2 text-orange-800 font-semibold">
                <Package className="w-5 h-5" />
                Missing Materials Detected
              </div>
              <p className="text-sm text-orange-700 mb-4">
                This order is waiting for materials. The following Purchase Orders were automatically generated:
              </p>
              <div className="space-y-2">
                {order.linkedPurchaseOrders.map((po) => (
                  <div key={po.id} className="flex items-center justify-between bg-white p-3 rounded-lg border border-orange-100">
                    <span className="font-mono font-medium text-sm text-text-primary">{po.id.slice(0,8)}</span>
                    <button onClick={() => navigate(`/purchase/${po.id}`)} className="text-sm text-primary hover:underline font-medium">
                      View Purchase Order
                    </button>
                  </div>
                ))}
              </div>
            </motion.div>
          )}


          {/* Components */}
          {components.length > 0 && (
            <motion.div className="table-container" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.08 }}>
              <div className="px-4 py-3 bg-bg-surface/50 border-b border-border">
                <h2 className="text-sm font-semibold text-text-primary">Components Required</h2>
              </div>
              <table className="table">
                <thead>
                  <tr><th>Component</th><th className="text-center">Qty Required</th><th>Unit</th></tr>
                </thead>
                <tbody>
                  {components.map((c, i) => (
                    <tr key={c.id ?? i}>
                      <td>
                        <p className="font-medium text-text-primary">{c.product?.name ?? c.component?.name ?? c.componentName ?? '—'}</p>
                        <p className="text-xs text-text-muted font-mono">{c.product?.sku ?? c.component?.sku ?? ''}</p>
                      </td>
                      <td className="text-center font-semibold">{c.quantity}</td>
                      <td className="text-text-muted text-sm">{c.unit?.name ?? '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </motion.div>
          )}

          {/* Work Orders */}
          {workOrders.length > 0 && (
            <motion.div className="table-container" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.12 }}>
              <div className="px-4 py-3 bg-bg-surface/50 border-b border-border">
                <h2 className="text-sm font-semibold text-text-primary">Work Orders</h2>
              </div>
              <table className="table">
                <thead>
                  <tr><th>#</th><th>Operation</th><th>Duration (min)</th><th>Status</th></tr>
                </thead>
                <tbody>
                  {workOrders.map((wo, i) => (
                    <tr key={wo.id ?? i}>
                      <td className="text-text-muted text-xs">{i + 1}</td>
                      <td>
                        <p className="font-medium text-text-primary">{wo.operation?.name ?? wo.name ?? '—'}</p>
                      </td>
                      <td className="text-text-secondary">{wo.durationMinutes ?? wo.duration ?? '—'}</td>
                      <td><StatusBadge status={labelStatus(wo.status ?? 'PENDING')} /></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </motion.div>
          )}
        </div>

        {/* Sidebar */}
        <div className="space-y-4">
          <motion.div className="card" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
            <h2 className="text-sm font-semibold text-text-primary mb-4">Production Progress</h2>
            <div className="space-y-3">
              {STATUS_STEPS.map((step, i) => {
                const done = i <= currentStep && status !== 'CANCELLED';
                const current = i === currentStep && status !== 'CANCELLED';
                return (
                  <div key={step} className="flex items-center gap-3">
                    <div className={`w-6 h-6 rounded-full flex items-center justify-center shrink-0 text-xs font-bold ${
                      done ? 'bg-primary text-white' : 'bg-bg-light text-text-muted border border-border'
                    }`}>{done ? '✓' : i + 1}</div>
                    <span className={`text-sm ${done ? 'text-text-primary font-medium' : 'text-text-muted'}`}>{step}</span>
                    {current && <span className="ml-auto text-[10px] px-2 py-0.5 rounded-full bg-primary/10 text-primary font-medium">Current</span>}
                  </div>
                );
              })}
            </div>
            {status === 'CANCELLED' && (
              <div className="mt-4 p-3 rounded-btn bg-danger/5 border border-danger/20">
                <p className="text-xs text-danger font-medium flex items-center gap-1.5">
                  <XCircle className="w-3.5 h-3.5" />This order has been cancelled
                </p>
              </div>
            )}
          </motion.div>

          <motion.div className="card" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
            <h2 className="text-sm font-semibold text-text-primary mb-3">Timestamps</h2>
            <div className="space-y-2 text-xs text-text-muted">
              {order.createdAt && <p>Created: <span className="text-text-secondary">{formatDateTime(order.createdAt)}</span></p>}
              {order.updatedAt && <p>Updated: <span className="text-text-secondary">{formatDateTime(order.updatedAt)}</span></p>}
            </div>
          </motion.div>
        </div>
      </div>

      {/* Action Modals */}
      {[
        { key: 'check',    title: 'Check Material Availability', body: 'This will check inventory and automatically generate Purchase Orders for missing components.', btn: 'Check Availability', btnClass: 'btn-primary', icon: Package, action: () => doAction(() => manufacturingApi.checkAvailability(id), 'Availability checked', 'check') },
        { key: 'start',    title: 'Start Production',             body: 'Component inventory will be consumed for this order.', btn: 'Start', btnClass: 'btn-warning', icon: Play, action: () => doAction(() => manufacturingApi.start(id), 'Production started', 'start') },
        { key: 'complete', title: 'Complete Manufacturing',        body: 'Finished goods will be added to inventory.', btn: 'Complete', btnClass: 'btn-success', icon: Trophy, action: () => doAction(() => manufacturingApi.complete(id), 'Manufacturing complete', 'complete') },
      ].map(m => (
        <AnimatePresence key={m.key}>
          {modal === m.key && (
            <motion.div className="modal-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              onClick={e => e.target === e.currentTarget && setModal(null)}>
              <motion.div className="modal" initial={{ opacity: 0, scale: 0.95, y: 16 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.95 }}>
                <div className="modal-header">
                  <h2 className="text-base font-semibold text-text-primary">{m.title}</h2>
                  <button onClick={() => setModal(null)} className="btn-ghost btn-icon"><XCircle className="w-4 h-4" /></button>
                </div>
                <div className="modal-body">
                  <p className="text-sm text-text-secondary">{m.body}</p>
                </div>
                <div className="modal-footer">
                  <button onClick={() => setModal(null)} className="btn-secondary">Cancel</button>
                  <button onClick={m.action} className={m.btnClass} disabled={actionLoading}>
                    {actionLoading
                      ? <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      : <m.icon className="w-4 h-4" />}
                    {m.btn}
                  </button>
                </div>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>
      ))}
    </PageWrapper>
  );
}
