import { PurchaseStatus, Prisma } from '@prisma/client';
import prisma from '../../config/database';
import { CreateVendorDto, UpdateVendorDto, CreatePurchaseOrderDto } from './purchase.validator';

const PO_INCLUDE = {
  vendor: { select: { id: true, name: true } },
  company: { select: { id: true, name: true } },
  items: {
    include: {
      product: { select: { id: true, sku: true, name: true, unit: { select: { symbol: true } } } },
    },
  },
} satisfies Prisma.PurchaseOrderInclude;

export class PurchaseRepository {
  // ─── Vendors ────────────────────────────────────────────────

  async findVendors(companyId?: string, page = 1, limit = 20) {
    const where: Prisma.VendorWhereInput = { deletedAt: null, ...(companyId && { companyId }) };
    const [data, total] = await Promise.all([
      prisma.vendor.findMany({ where, skip: (page - 1) * limit, take: limit, orderBy: { name: 'asc' } }),
      prisma.vendor.count({ where }),
    ]);
    return { data, total };
  }

  async findVendorById(id: string) {
    return prisma.vendor.findFirst({ where: { id, deletedAt: null } });
  }

  async createVendor(dto: CreateVendorDto) {
    return prisma.vendor.create({ data: dto });
  }

  async updateVendor(id: string, dto: UpdateVendorDto) {
    return prisma.vendor.update({ where: { id }, data: dto });
  }

  async softDeleteVendor(id: string) {
    return prisma.vendor.update({ where: { id }, data: { deletedAt: new Date() } });
  }

  // ─── Purchase Orders ─────────────────────────────────────────

  async findOrders(filters: {
    page: number;
    limit: number;
    companyId?: string;
    vendorId?: string;
    status?: PurchaseStatus;
    autoGenerated?: boolean;
  }) {
    const where: Prisma.PurchaseOrderWhereInput = {
      ...(filters.companyId && { companyId: filters.companyId }),
      ...(filters.vendorId && { vendorId: filters.vendorId }),
      ...(filters.status && { status: filters.status }),
      ...(filters.autoGenerated !== undefined && { autoGenerated: filters.autoGenerated }),
    };
    const [data, total] = await Promise.all([
      prisma.purchaseOrder.findMany({
        where, include: PO_INCLUDE,
        skip: (filters.page - 1) * filters.limit,
        take: filters.limit,
        orderBy: { createdAt: 'desc' },
      }),
      prisma.purchaseOrder.count({ where }),
    ]);
    return { data, total };
  }

  async findOrderById(id: string, tx?: Prisma.TransactionClient) {
    const client = tx || prisma;
    return client.purchaseOrder.findUnique({ where: { id }, include: PO_INCLUDE });
  }

  async createOrder(dto: CreatePurchaseOrderDto) {
    const totalAmount = dto.items.reduce((sum, i) => sum + i.quantity * i.unitPrice, 0);
    return prisma.purchaseOrder.create({
      data: {
        companyId: dto.companyId,
        vendorId: dto.vendorId,
        notes: dto.notes,
        autoGenerated: dto.autoGenerated,
        totalAmount,
        items: {
          create: dto.items.map((i) => ({
            productId: i.productId,
            quantity: i.quantity,
            unitPrice: i.unitPrice,
          })),
        },
      },
      include: PO_INCLUDE,
    });
  }

  async updateOrderStatus(id: string, status: PurchaseStatus, tx?: Prisma.TransactionClient) {
    const client = tx || prisma;
    return client.purchaseOrder.update({ where: { id }, data: { status } });
  }
}

export const purchaseRepository = new PurchaseRepository();
