import { z } from 'zod';

export const createVendorSchema = z.object({
  companyId: z.string().min(1),
  name: z.string().min(2),
  email: z.string().email().optional(),
  phone: z.string().optional(),
  address: z.string().optional(),
});

export const updateVendorSchema = createVendorSchema.partial().omit({ companyId: true });

export const createPurchaseOrderSchema = z.object({
  companyId: z.string().min(1),
  vendorId: z.string().min(1),
  notes: z.string().optional(),
  autoGenerated: z.boolean().default(false),
  items: z
    .array(
      z.object({
        productId: z.string().min(1),
        quantity: z.coerce.number().positive(),
        unitPrice: z.coerce.number().min(0),
      }),
    )
    .min(1, 'At least one item is required'),
});

export const receivePurchaseOrderSchema = z.object({
  warehouseId: z.string().min(1),
  items: z
    .array(
      z.object({
        purchaseOrderItemId: z.string().min(1),
        receivedQty: z.coerce.number().positive(),
      }),
    )
    .min(1, 'At least one receipt item required'),
});

export const purchaseOrderQuerySchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
  companyId: z.string().min(1).optional(),
  vendorId: z.string().min(1).optional(),
  status: z.enum(['DRAFT', 'CONFIRMED', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CANCELLED']).optional(),
  autoGenerated: z.enum(['true', 'false']).transform(v => v === 'true').optional(),
});

export type CreateVendorDto = z.infer<typeof createVendorSchema>;
export type UpdateVendorDto = z.infer<typeof updateVendorSchema>;
export type CreatePurchaseOrderDto = z.infer<typeof createPurchaseOrderSchema>;
export type ReceivePurchaseOrderDto = z.infer<typeof receivePurchaseOrderSchema>;
export type PurchaseOrderQueryDto = z.infer<typeof purchaseOrderQuerySchema>;
