import { Router } from 'express';
import { Role } from '@prisma/client';
import { purchaseController } from './purchase.controller';
import { asyncHandler } from '../../common/utils/asyncHandler';
import { validate } from '../../common/middleware/validate.middleware';
import { authenticate } from '../../common/middleware/auth.middleware';
import { authorize } from '../../common/middleware/rbac.middleware';
import {
  createVendorSchema, updateVendorSchema,
  createPurchaseOrderSchema, receivePurchaseOrderSchema, purchaseOrderQuerySchema,
} from './purchase.validator';
import { idParamSchema } from '../../common/validators/common.validator';

const router = Router();
router.use(authenticate);

const purchaseRoles = [Role.ADMIN, Role.BUSINESS_OWNER, Role.PURCHASE_USER, Role.INVENTORY_MANAGER];

/**
 * @swagger
 * tags:
 *   name: Purchase
 *   description: Vendors and Purchase Order management
 */

// ─── Vendor Routes ───────────────────────────────────────────

/**
 * @swagger
 * /vendors:
 *   get:
 *     tags: [Purchase]
 *     summary: List all vendors
 *     responses:
 *       200:
 *         description: Vendor list
 */
router.get('/vendors', authorize(...purchaseRoles), asyncHandler(purchaseController.listVendors.bind(purchaseController)));
router.post('/vendors', authorize(...purchaseRoles), validate(createVendorSchema), asyncHandler(purchaseController.createVendor.bind(purchaseController)));
router.put('/vendors/:id', authorize(...purchaseRoles), validate(idParamSchema, 'params'), validate(updateVendorSchema), asyncHandler(purchaseController.updateVendor.bind(purchaseController)));
router.delete('/vendors/:id', authorize(Role.ADMIN, Role.BUSINESS_OWNER), validate(idParamSchema, 'params'), asyncHandler(purchaseController.deleteVendor.bind(purchaseController)));

// ─── Purchase Order Routes ───────────────────────────────────

/**
 * @swagger
 * /purchase-orders:
 *   get:
 *     tags: [Purchase]
 *     summary: List purchase orders
 *     parameters:
 *       - in: query
 *         name: status
 *         schema: { type: string, enum: [DRAFT, CONFIRMED, PARTIALLY_RECEIVED, FULLY_RECEIVED, CANCELLED] }
 *       - in: query
 *         name: autoGenerated
 *         schema: { type: boolean }
 *         description: Filter auto-generated orders from procurement automation
 *     responses:
 *       200:
 *         description: Paginated purchase order list
 */
router.get('/purchase-orders', authorize(...purchaseRoles), validate(purchaseOrderQuerySchema, 'query'), asyncHandler(purchaseController.listOrders.bind(purchaseController)));
router.get('/purchase-orders/export', authorize(Role.ADMIN, Role.BUSINESS_OWNER), asyncHandler(purchaseController.exportExcel.bind(purchaseController)));
router.get('/purchase-orders/:id', authorize(...purchaseRoles), validate(idParamSchema, 'params'), asyncHandler(purchaseController.getOrderById.bind(purchaseController)));

/**
 * @swagger
 * /purchase-orders:
 *   post:
 *     tags: [Purchase]
 *     summary: Create a purchase order (DRAFT)
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [companyId, vendorId, items]
 *             properties:
 *               companyId: { type: string, format: uuid }
 *               vendorId: { type: string, format: uuid }
 *               items:
 *                 type: array
 *                 items:
 *                   type: object
 *                   properties:
 *                     productId: { type: string, format: uuid }
 *                     quantity: { type: number }
 *                     unitPrice: { type: number }
 *     responses:
 *       201:
 *         description: Purchase order created
 */
router.post('/purchase-orders', authorize(...purchaseRoles), validate(createPurchaseOrderSchema), asyncHandler(purchaseController.createOrder.bind(purchaseController)));

/**
 * @swagger
 * /purchase-orders/{id}/confirm:
 *   post:
 *     tags: [Purchase]
 *     summary: Confirm purchase order
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Order confirmed
 */
router.post('/purchase-orders/:id/confirm', authorize(...purchaseRoles), validate(idParamSchema, 'params'), asyncHandler(purchaseController.confirmOrder.bind(purchaseController)));

/**
 * @swagger
 * /purchase-orders/{id}/receive:
 *   post:
 *     tags: [Purchase]
 *     summary: Receive goods — increases inventory, creates stock ledger entry
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string, format: uuid }
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [warehouseId, items]
 *             properties:
 *               warehouseId: { type: string, format: uuid }
 *               items:
 *                 type: array
 *                 items:
 *                   type: object
 *                   properties:
 *                     purchaseOrderItemId: { type: string, format: uuid }
 *                     receivedQty: { type: number }
 *     responses:
 *       200:
 *         description: Goods received, inventory updated
 */
router.post('/purchase-orders/:id/receive', authorize(...purchaseRoles), validate(idParamSchema, 'params'), validate(receivePurchaseOrderSchema), asyncHandler(purchaseController.receiveOrder.bind(purchaseController)));

/**
 * @swagger
 * /purchase-orders/{id}:
 *   delete:
 *     tags: [Purchase]
 *     summary: Delete a purchase order
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Order deleted
 */
router.delete('/purchase-orders/:id', authorize(Role.ADMIN, Role.BUSINESS_OWNER), validate(idParamSchema, 'params'), asyncHandler(purchaseController.deleteOrder.bind(purchaseController)));

export default router;
