import prisma from '../../config/database';
import { OrderStatus, PurchaseStatus, ManufacturingStatus } from '@prisma/client';

export class DashboardService {
  /**
   * Overall ERP summary metrics
   */
  async getSummary(companyId?: string) {
    const companyFilter = companyId ? { companyId } : {};

    const [
      totalProducts,
      totalCustomers,
      totalVendors,
      totalInventoryValue,
      lowStockCount,
      recentAuditLogs,
    ] = await Promise.all([
      prisma.product.count({ where: { ...companyFilter, deletedAt: null } }),
      prisma.customer.count({ where: { ...companyFilter, deletedAt: null } }),
      prisma.vendor.count({ where: { ...companyFilter, deletedAt: null } }),
      prisma.inventory.aggregate({
        where: companyId ? { warehouse: { companyId } } : {},
        _sum: { onHandQty: true },
      }),
      prisma.inventory.count({
        where: {
          ...(companyId ? { warehouse: { companyId } } : {}),
          freeToUseQty: { lte: 5 },
        },
      }),
      prisma.auditLog.findMany({
        where: companyFilter,
        include: { user: { select: { name: true } } },
        orderBy: { timestamp: 'desc' },
        take: 10,
      }),
    ]);

    return {
      totalProducts,
      totalCustomers,
      totalVendors,
      totalInventoryUnits: totalInventoryValue._sum.onHandQty || 0,
      lowStockProductCount: lowStockCount,
      recentAuditLogs,
    };
  }

  /**
   * Sales dashboard metrics
   */
  async getSalesDashboard(companyId?: string) {
    const companyFilter = companyId ? { companyId } : {};

    const [
      totalOrders,
      draftOrders,
      confirmedOrders,
      partiallyDelivered,
      fullyDelivered,
      cancelledOrders,
      totalRevenue,
      recentOrders,
    ] = await Promise.all([
      prisma.salesOrder.count({ where: companyFilter }),
      prisma.salesOrder.count({ where: { ...companyFilter, status: OrderStatus.DRAFT } }),
      prisma.salesOrder.count({ where: { ...companyFilter, status: OrderStatus.CONFIRMED } }),
      prisma.salesOrder.count({ where: { ...companyFilter, status: OrderStatus.PARTIALLY_DELIVERED } }),
      prisma.salesOrder.count({ where: { ...companyFilter, status: OrderStatus.FULLY_DELIVERED } }),
      prisma.salesOrder.count({ where: { ...companyFilter, status: OrderStatus.CANCELLED } }),
      prisma.salesOrder.aggregate({
        where: { ...companyFilter, status: { in: [OrderStatus.FULLY_DELIVERED, OrderStatus.PARTIALLY_DELIVERED] } },
        _sum: { totalAmount: true },
      }),
      prisma.salesOrder.findMany({
        where: companyFilter,
        include: { customer: { select: { name: true } } },
        orderBy: { createdAt: 'desc' },
        take: 5,
      }),
    ]);

    return {
      totalOrders,
      byStatus: { draftOrders, confirmedOrders, partiallyDelivered, fullyDelivered, cancelledOrders },
      pendingDeliveries: confirmedOrders + partiallyDelivered,
      totalRevenue: totalRevenue._sum.totalAmount || 0,
      recentOrders,
    };
  }

  /**
   * Purchase dashboard metrics
   */
  async getPurchaseDashboard(companyId?: string) {
    const companyFilter = companyId ? { companyId } : {};

    const [
      totalOrders,
      draftOrders,
      confirmedOrders,
      partiallyReceived,
      fullyReceived,
      totalSpend,
      autoGeneratedOrders,
      recentOrders,
    ] = await Promise.all([
      prisma.purchaseOrder.count({ where: companyFilter }),
      prisma.purchaseOrder.count({ where: { ...companyFilter, status: PurchaseStatus.DRAFT } }),
      prisma.purchaseOrder.count({ where: { ...companyFilter, status: PurchaseStatus.CONFIRMED } }),
      prisma.purchaseOrder.count({ where: { ...companyFilter, status: PurchaseStatus.PARTIALLY_RECEIVED } }),
      prisma.purchaseOrder.count({ where: { ...companyFilter, status: PurchaseStatus.FULLY_RECEIVED } }),
      prisma.purchaseOrder.aggregate({
        where: { ...companyFilter, status: PurchaseStatus.FULLY_RECEIVED },
        _sum: { totalAmount: true },
      }),
      prisma.purchaseOrder.count({ where: { ...companyFilter, autoGenerated: true } }),
      prisma.purchaseOrder.findMany({
        where: companyFilter,
        include: { vendor: { select: { name: true } } },
        orderBy: { createdAt: 'desc' },
        take: 5,
      }),
    ]);

    return {
      totalOrders,
      byStatus: { draftOrders, confirmedOrders, partiallyReceived, fullyReceived },
      pendingReceipts: confirmedOrders + partiallyReceived,
      totalSpend: totalSpend._sum.totalAmount || 0,
      autoGeneratedOrders,
      recentOrders,
    };
  }

  /**
   * Manufacturing dashboard metrics
   */
  async getManufacturingDashboard(companyId?: string) {
    const companyFilter = companyId ? { companyId } : {};

    const [
      totalOrders,
      draftOrders,
      waitingForMaterials,
      readyForProduction,
      inProduction,
      completed,
      autoGeneratedOrders,
      recentOrders,
    ] = await Promise.all([
      prisma.manufacturingOrder.count({ where: companyFilter }),
      prisma.manufacturingOrder.count({ where: { ...companyFilter, status: ManufacturingStatus.DRAFT } }),
      prisma.manufacturingOrder.count({ where: { ...companyFilter, status: ManufacturingStatus.WAITING_FOR_MATERIALS } }),
      prisma.manufacturingOrder.count({ where: { ...companyFilter, status: ManufacturingStatus.READY_FOR_PRODUCTION } }),
      prisma.manufacturingOrder.count({ where: { ...companyFilter, status: ManufacturingStatus.IN_PRODUCTION } }),
      prisma.manufacturingOrder.count({ where: { ...companyFilter, status: ManufacturingStatus.COMPLETED } }),
      prisma.manufacturingOrder.count({ where: { ...companyFilter, autoGenerated: true } }),
      prisma.manufacturingOrder.findMany({
        where: companyFilter,
        include: { product: { select: { name: true, sku: true } } },
        orderBy: { createdAt: 'desc' },
        take: 5,
      }),
    ]);

    return {
      totalOrders,
      byStatus: { 
        draftOrders, 
        waitingForMaterials,
        readyForProduction,
        inProduction,
        completed
      },
      activeProduction: inProduction + readyForProduction,
      completedOrders: completed,
      autoGeneratedOrders,
      recentOrders,
    };
  }

  /**
   * Inventory dashboard metrics
   */
  async getInventoryDashboard(companyId?: string) {
    const warehouseFilter = companyId ? { warehouse: { companyId } } : {};

    const [
      totalInventoryRecords,
      lowStockItems,
      zeroStockItems,
      topProducts,
      recentMovements,
    ] = await Promise.all([
      prisma.inventory.count({ where: warehouseFilter }),
      prisma.inventory.findMany({
        where: { ...warehouseFilter, freeToUseQty: { gt: 0, lte: 10 } },
        include: { product: { select: { sku: true, name: true } }, warehouse: { select: { name: true } } },
        orderBy: { freeToUseQty: 'asc' },
        take: 10,
      }),
      prisma.inventory.count({ where: { ...warehouseFilter, onHandQty: 0 } }),
      prisma.inventory.findMany({
        where: warehouseFilter,
        include: { product: { select: { sku: true, name: true } } },
        orderBy: { onHandQty: 'desc' },
        take: 10,
      }),
      prisma.stockLedger.findMany({
        where: companyId ? { warehouse: { companyId } } : {},
        include: {
          product: { select: { sku: true, name: true } },
          warehouse: { select: { name: true } },
        },
        orderBy: { createdAt: 'desc' },
        take: 10,
      }),
    ]);

    return {
      totalInventoryRecords,
      zeroStockItems,
      lowStockItems,
      topStockedProducts: topProducts,
      recentMovements,
    };
  }
}

export const dashboardService = new DashboardService();
