import { ProcurementType } from '@prisma/client';
import prisma from '../../config/database';
import { procurementRepository } from './procurement.repository';
import { AppError } from '../../common/utils/AppError';
import { MESSAGES } from '../../common/constants/messages';
import { logger } from '../../config/logger';
import { eventEmitter } from '../../common/events/eventEmitter';
import { ERP_EVENTS } from '../../common/events/events.types';

// ============================================================
// PROCUREMENT AUTOMATION SERVICE
//
// Triggered when Sales Confirm detects a shortage and the
// product has procure_on_demand = true.
//
// Flow:
//   calculateShortage()
//     → if PURCHASE: generatePurchaseOrder()
//     → if MANUFACTURING: generateManufacturingOrder()
//     → log to procurement_logs
// ============================================================

interface ProcurementTrigger {
  companyId: string;
  productId: string;
  shortageQty: number;
  triggerSource: string;
  userId?: string;
}

export class ProcurementService {
  /**
   * Main entry point — called by event listener or directly
   */
  async triggerProcurement(trigger: ProcurementTrigger): Promise<void> {
    const { companyId, productId, shortageQty, triggerSource } = trigger;

    try {
      const product = await prisma.product.findFirst({
        where: { id: productId, deletedAt: null },
        include: {
          vendor: true,
          defaultBom: { include: { components: true, operations: true } },
        },
      });

      if (!product) {
        logger.warn(`Procurement: product ${productId} not found`);
        return;
      }

      if (!product.procureOnDemand) {
        logger.info(`Procurement: product ${product.sku} has procure_on_demand=false, skipping`);
        return;
      }

      let generatedOrderId: string | undefined;
      let generatedOrderType: string;

      if (product.procurementType === ProcurementType.PURCHASE) {
        const po = await this.generatePurchaseOrder(
          companyId,
          product,
          shortageQty,
          triggerSource,
        );
        generatedOrderId = po?.id;
        generatedOrderType = 'PURCHASE_ORDER';
      } else {
        const mo = await this.generateManufacturingOrder(
          companyId,
          product,
          shortageQty,
          triggerSource,
        );
        generatedOrderId = mo?.id;
        generatedOrderType = 'MANUFACTURING_ORDER';
      }

      // Log the procurement action
      await procurementRepository.logProcurement({
        companyId,
        triggerSource,
        productId,
        shortageQty,
        generatedOrderType,
        generatedOrderId,
      });

      // Emit event for further processing
      eventEmitter.emit(ERP_EVENTS.PROCUREMENT_TRIGGERED, {
        companyId,
        productId,
        shortageQty,
        generatedOrderType: product.procurementType,
        generatedOrderId,
      });

      logger.info(
        `Procurement: auto-generated ${generatedOrderType} for product ${product.sku}, qty: ${shortageQty}`,
      );
    } catch (error) {
      logger.error('Procurement automation error', { error, trigger });
    }
  }

  /**
   * Auto-generate a Purchase Order for shortage
   */
  private async generatePurchaseOrder(
    companyId: string,
    product: {
      id: string;
      sku: string;
      costPrice: unknown;
      vendorId: string | null;
      vendor: { id: string } | null;
    },
    shortageQty: number,
    triggerSource: string,
  ) {
    if (!product.vendorId || !product.vendor) {
      logger.warn(
        `Procurement: product ${product.sku} has no vendor configured — cannot auto-create PO`,
      );
      return null;
    }

    return prisma.purchaseOrder.create({
      data: {
        companyId,
        vendorId: product.vendorId,
        autoGenerated: true,
        notes: `Auto-generated by procurement engine. Trigger: ${triggerSource}`,
        totalAmount: Number(product.costPrice) * shortageQty,
        items: {
          create: [
            {
              productId: product.id,
              quantity: shortageQty,
              unitPrice: Number(product.costPrice),
            },
          ],
        },
      },
    });
  }

  /**
   * Auto-generate a Manufacturing Order for shortage
   */
  private async generateManufacturingOrder(
    companyId: string,
    product: {
      id: string;
      sku: string;
      bomId: string | null;
      defaultBom: { id: string } | null;
    },
    shortageQty: number,
    triggerSource: string,
  ) {
    if (!product.bomId || !product.defaultBom) {
      logger.warn(
        `Procurement: product ${product.sku} has no BOM configured — cannot auto-create MO`,
      );
      return null;
    }

    // Use the first available warehouse for this company
    const warehouse = await prisma.warehouse.findFirst({ where: { companyId } });
    if (!warehouse) {
      logger.warn(`Procurement: no warehouse found for company ${companyId}`);
      return null;
    }

    return prisma.manufacturingOrder.create({
      data: {
        companyId,
        bomId: product.bomId,
        productId: product.id,
        quantity: shortageQty,
        warehouseId: warehouse.id,
        autoGenerated: true,
        notes: `Auto-generated by procurement engine. Trigger: ${triggerSource}`,
      },
    });
  }

  /**
   * Get procurement logs
   */
  async getLogs(companyId?: string, page = 1, limit = 20) {
    return procurementRepository.findLogs(companyId, page, limit);
  }

  /**
   * Manual procurement trigger (for testing/demo)
   */
  async manualTrigger(
    productId: string,
    shortageQty: number,
    companyId: string,
    userId: string,
  ) {
    const product = await prisma.product.findFirst({
      where: { id: productId, companyId, deletedAt: null },
    });

    if (!product) throw AppError.notFound(MESSAGES.PRODUCTS.NOT_FOUND);
    if (!product.procureOnDemand) {
      throw AppError.badRequest('Product does not have procure_on_demand enabled');
    }

    await this.triggerProcurement({
      companyId,
      productId,
      shortageQty,
      triggerSource: `MANUAL:${userId}`,
      userId,
    });

    return { message: MESSAGES.PROCUREMENT.TRIGGERED, productId, shortageQty };
  }
}

export const procurementService = new ProcurementService();

// ============================================================
// Register event listener for procurement automation
// Called from app.ts after services are initialised
// ============================================================
export function registerProcurementListeners() {
  eventEmitter.on(
    ERP_EVENTS.PROCUREMENT_TRIGGERED,
    async (trigger: {
      companyId: string;
      productId: string;
      shortageQty: number;
      triggerSource: string;
      userId?: string;
    }) => {
      // Avoid re-triggering procurement events from procurement itself
      if (trigger.triggerSource?.startsWith('PROCUREMENT:')) return;

      await procurementService.triggerProcurement(trigger);
    },
  );

  logger.info('✅ Procurement automation event listener registered');
}
