import { z } from 'zod';

export const createManufacturingOrderSchema = z.object({
  companyId: z.string().uuid(),
  bomId: z.string().uuid('BOM ID is required'),
  productId: z.string().uuid('Finished product ID is required'),
  quantity: z.coerce.number().positive('Quantity must be positive'),
  warehouseId: z.string().uuid('Warehouse ID is required'),
  notes: z.string().optional(),
  autoGenerated: z.boolean().default(false),
});

export const manufacturingOrderQuerySchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
  companyId: z.string().uuid().optional(),
  status: z.enum(['DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'DONE', 'CANCELLED']).optional(),
  autoGenerated: z.enum(['true', 'false']).transform(v => v === 'true').optional(),
});

export type CreateManufacturingOrderDto = z.infer<typeof createManufacturingOrderSchema>;
export type ManufacturingOrderQueryDto = z.infer<typeof manufacturingOrderQuerySchema>;
