import { ManufacturingStatus, Prisma } from '@prisma/client';
import prisma from '../../config/database';
import { CreateManufacturingOrderDto } from './manufacturing.validator';

const MO_INCLUDE = {
  bom: {
    include: {
      components: { include: { product: true, unit: true } },
      operations: { orderBy: { sequence: 'asc' as const } },
    },
  },
  product: { select: { id: true, sku: true, name: true } },
  company: { select: { id: true, name: true } },
  warehouse: { select: { id: true, name: true } },
  workOrders: { include: { operation: true } },
  linkedPurchaseOrders: { include: { items: true } },
} satisfies Prisma.ManufacturingOrderInclude;

export class ManufacturingRepository {
  async findAll(filters: {
    companyId?: string;
    status?: ManufacturingStatus;
    autoGenerated?: boolean;
    page: number;
    limit: number;
  }) {
    const where: Prisma.ManufacturingOrderWhereInput = {
      ...(filters.companyId && { companyId: filters.companyId }),
      ...(filters.status && { status: filters.status }),
      ...(filters.autoGenerated !== undefined && { autoGenerated: filters.autoGenerated }),
    };

    const [data, total] = await Promise.all([
      prisma.manufacturingOrder.findMany({
        where,
        include: MO_INCLUDE,
        skip: (filters.page - 1) * filters.limit,
        take: filters.limit,
        orderBy: { createdAt: 'desc' },
      }),
      prisma.manufacturingOrder.count({ where }),
    ]);
    return { data, total };
  }

  async findById(id: string, tx?: Prisma.TransactionClient) {
    const client = tx || prisma;
    return client.manufacturingOrder.findUnique({ where: { id }, include: MO_INCLUDE });
  }

  async create(dto: CreateManufacturingOrderDto) {
    return prisma.manufacturingOrder.create({
      data: {
        companyId: dto.companyId,
        bomId: dto.bomId,
        productId: dto.productId,
        quantity: dto.quantity,
        warehouseId: dto.warehouseId,
        notes: dto.notes,
        autoGenerated: dto.autoGenerated,
      },
      include: MO_INCLUDE,
    });
  }

  async updateStatus(id: string, status: ManufacturingStatus, tx?: Prisma.TransactionClient) {
    const client = tx || prisma;
    return client.manufacturingOrder.update({ where: { id }, data: { status } });
  }
}

export const manufacturingRepository = new ManufacturingRepository();
