import { Router } from 'express';
import { Role } from '@prisma/client';
import { manufacturingController } from './manufacturing.controller';
import { asyncHandler } from '../../common/utils/asyncHandler';
import { validate } from '../../common/middleware/validate.middleware';
import { authenticate } from '../../common/middleware/auth.middleware';
import { authorize } from '../../common/middleware/rbac.middleware';
import { createManufacturingOrderSchema, manufacturingOrderQuerySchema } from './manufacturing.validator';
import { idParamSchema } from '../../common/validators/common.validator';

const router = Router();
router.use(authenticate);

const mfgRoles = [Role.ADMIN, Role.BUSINESS_OWNER, Role.MANUFACTURING_USER, Role.INVENTORY_MANAGER];

/**
 * @swagger
 * tags:
 *   name: Manufacturing
 *   description: Manufacturing Orders and Work Orders
 */

/**
 * @swagger
 * /manufacturing-orders:
 *   get:
 *     tags: [Manufacturing]
 *     summary: List manufacturing orders
 *     parameters:
 *       - in: query
 *         name: status
 *         schema: { type: string, enum: [DRAFT, CONFIRMED, IN_PROGRESS, DONE, CANCELLED] }
 *       - in: query
 *         name: autoGenerated
 *         schema: { type: boolean }
 *     responses:
 *       200:
 *         description: Paginated list of manufacturing orders
 */
router.get('/', authorize(...mfgRoles), validate(manufacturingOrderQuerySchema, 'query'), asyncHandler(manufacturingController.list.bind(manufacturingController)));
router.get('/:id', authorize(...mfgRoles), validate(idParamSchema, 'params'), asyncHandler(manufacturingController.getById.bind(manufacturingController)));

/**
 * @swagger
 * /manufacturing-orders:
 *   post:
 *     tags: [Manufacturing]
 *     summary: Create a manufacturing order (DRAFT)
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required: [companyId, bomId, productId, quantity, warehouseId]
 *             properties:
 *               companyId: { type: string, format: uuid }
 *               bomId: { type: string, format: uuid }
 *               productId: { type: string, format: uuid }
 *               quantity: { type: number, minimum: 1 }
 *               warehouseId: { type: string, format: uuid }
 *     responses:
 *       201:
 *         description: Manufacturing order created in DRAFT state
 */
router.post('/', authorize(...mfgRoles), validate(createManufacturingOrderSchema), asyncHandler(manufacturingController.create.bind(manufacturingController)));

/**
 * @swagger
 * /manufacturing-orders/{id}/confirm:
 *   post:
 *     tags: [Manufacturing]
 *     summary: Confirm order — generates work orders from BoM operations
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Order confirmed, work orders created
 */
router.post('/:id/confirm', authorize(...mfgRoles), validate(idParamSchema, 'params'), asyncHandler(manufacturingController.confirm.bind(manufacturingController)));

/**
 * @swagger
 * /manufacturing-orders/{id}/start:
 *   post:
 *     tags: [Manufacturing]
 *     summary: Start manufacturing — reserves component inventory
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Manufacturing started, components reserved
 */
router.post('/:id/start', authorize(...mfgRoles), validate(idParamSchema, 'params'), asyncHandler(manufacturingController.start.bind(manufacturingController)));

/**
 * @swagger
 * /manufacturing-orders/{id}/complete:
 *   post:
 *     tags: [Manufacturing]
 *     summary: Complete manufacturing — consumes components, produces finished goods
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Manufacturing completed, inventory updated
 */
router.post('/:id/complete', authorize(...mfgRoles), validate(idParamSchema, 'params'), asyncHandler(manufacturingController.complete.bind(manufacturingController)));

/**
 * @swagger
 * /manufacturing-orders/{id}:
 *   delete:
 *     tags: [Manufacturing]
 *     summary: Delete a manufacturing order
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema: { type: string, format: uuid }
 *     responses:
 *       200:
 *         description: Order deleted
 */
router.delete('/:id', authorize(Role.ADMIN, Role.BUSINESS_OWNER), validate(idParamSchema, 'params'), asyncHandler(manufacturingController.deleteOrder.bind(manufacturingController)));

export default router;
