import { z } from 'zod';

export const createManufacturingOrderSchema = z.object({
  companyId: z.string().min(1),
  bomId: z.string().min(1),
  productId: z.string().min(1),
  quantity: z.coerce.number().positive('Quantity must be positive'),
  warehouseId: z.string().min(1),
  notes: z.string().optional(),
  autoGenerated: z.boolean().default(false),
});

export const manufacturingOrderQuerySchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
  companyId: z.string().min(1).optional(),
  status: z.enum(['DRAFT', 'WAITING_FOR_MATERIALS', 'READY_FOR_PRODUCTION', 'IN_PRODUCTION', 'COMPLETED', 'CANCELLED']).optional(),
  autoGenerated: z.enum(['true', 'false']).transform(v => v === 'true').optional(),
});

export type CreateManufacturingOrderDto = z.infer<typeof createManufacturingOrderSchema>;
export type ManufacturingOrderQueryDto = z.infer<typeof manufacturingOrderQuerySchema>;
